### ISSUE TITLE
Unable to Reproduce Paper Results due to Density Artifacts while Image Stippling

### ISSUE THREAD

**Issue by tylermorganwall** [iribis/filtered-sliced-optimal-transport#2]
I have been trying to reproduce the results seen in the paper with the provided code, and I have been unable to generate the nicely stippled CMYK plots seen in the paper.  I am using the code unchanged and as provided. The FSOT routine produces streaks of high density points upon convergence for the given image. For example, 10000 steps at 512 projections per step yields this: 

Here's an example:
```base
./FSOT -n 4096 -p 10000 --nbproj 512 --method image -i resources/colored_sea.png -o image.dat
python3 render_color_img.py image.dat image.png resources/colored_sea.png 0.133337 0.470049 0.719257 1.0
```
![image](https://github.com/iribis/filtered-sliced-optimal-transport/assets/297609/b188cd65-b5b5-4ed1-a58c-c7feb86763fc)

**Comment by tylermorganwall** [comment]
I believe I figured out the issue--I determined I originally built the library without -DCMAKE_BUILD_TYPE=Release, rebuilding it fixed the problem.

**Comment by iribis** [comment]
I've tried to reproduce the error and it may also be caused by a slightly too low learning rate (image_based_sot.h l.452). It is possible to increase it a little to speed up convergence (eg lr = 0.003).
